### ISSUE TITLE
[Bug] SkyblockAddons-1.9.0-beta.6 and above versions can't properly load on win 11, the game crashes when loading the mods

### ISSUE THREAD

**Issue by xBunyHop** [Fix3dll/SkyblockAddons#61]
### Bug Description

Game crashes when trying to launch version SkyblockAddons-1.9.0-beta.6 and versions above.
Last working version is SkyblockAddons-1.9.0-beta.5

### SBA Version

SkyblockAddons-1.9.0-beta.6 and above

### Other Installed Mods

LabyMod Client (1.8.9) (Forge x Optifine)
NotEnoughUpdates-2.3.3
Dungeon_Rooms-3.4.1

### Operating System

Windows 11 Pro 23H2

### Crash Report

https://paste.labymod.net/suquwoyebazogucequna

**Comment by Fix3dll** [comment]
@xBunyHop LabyMod is not supported. Try to use [MinecraftForge 1.8.9](https://files.minecraftforge.net/net/minecraftforge/forge/index_1.8.9.html)

**Comment by xBunyHop** [comment]
It's a shame, it was working fine until beta .6

Thanks for such fast reply!

**Comment by Fix3dll** [comment]
@xBunyHop it is because i change MixinExtras with ASM and downgrade Mixin from 0.8.5 to 0.7.11 because of compability issues. The problem you mentioned is caused by LabyMod's interaction with ASM. But I would like to remind you that LabyMod is not open source and last time I looked I couldn't find any documentation. If anyone is willing to help solve this issue, I'd be happy to accept a pull request.

**Comment by xBunyHop** [comment]
I will try to reach out to someone from LabyMod regarding this issue. They're very open to community in terms of feedback and bug fixes. I thank you again for such fast reply, I'll forward your response to someone at LabyMod.
